### ISSUE TITLE
Chart not Found

### ISSUE THREAD

**Issue by ShoGinn** [mfrelink/OpenFLIXR.LandingPage#1]
The hard drive badge in the middle (the hard drive one) is hard routed to sda.

I use your KVM image on ProxMox and use virtio (vda instead of sda) not a huge problem, but can you  query net data somehow to get the drives instead of a hard link?

**Comment by mfrelink** [comment]
Confirmed. Will see if I can query netdata or come up with another fix.

**Comment by mfrelink** [comment]
Fixed in 1.7.0
