### ISSUE TITLE
The page waits for the iframe to load before the javascript onload is triggered

### ISSUE THREAD

**Issue by syserr0r** [mfrelink/OpenFLIXR.LandingPage#3]
I removed the `src` attribute from the iframe and added this line to the end of the 'checkServer' function:
`document.getElementById("latest-iframe").src = '/latest';`

This causes the iframe to be loaded after the body javascript has been called and gives a significant improvement to page-load speed (over 1000ms reduction)

**Comment by mfrelink** [comment]
Fixed in 1.7.0
