### ISSUE TITLE
The SDA badge does not show

### ISSUE THREAD

**Issue by syserr0r** [mfrelink/OpenFLIXR.LandingPage#4]
Using the ESXi image, the SDA badge does not show (as /dev/sda1 is a volume not a mountpoint and netdata seems to identify the mountpoint not the mounded volume)

I changed the `img src` in two places from:
`/netdata/api/v1/badge.svg?chart=disk_space.sda1&label=SDA&precision=1&units=` ...
to
`/netdata/api/v1/badge.svg?chart=disk_space._&label=SDA&precision=1&units=` ...

This shows me space usage on the openflixr VM

If you wish to show the space of one of the mountpoints then this will need adjusting to say:
`/netdata/api/v1/badge.svg?chart=disk_space._mnt_series&label=SDA&precision=1&units=` ...
(For the `/mnt/series` mountpoint in this example)

**Comment by mfrelink** [comment]
Fixed in 1.7.0
